### ISSUE TITLE
Fix broken Priority column

### ISSUE THREAD

**Issue by gl0om** [use-the-force/gitlab-board#11]
![Снимок экрана 2023-05-02 в 17 21 46](https://user-images.githubusercontent.com/634726/235695160-090890c0-b3dd-4b82-a598-e1ffb9c25933.png)

![Снимок экрана 2023-05-02 в 17 28 20](https://user-images.githubusercontent.com/634726/235696981-8361655c-f93f-491c-93fa-028c9e1c0077.png)

Priority is not displayed in both types of views

**Comment by stereoshoots** [comment]
Could not reproduce the error. Tried in FF, Safari, Opera and Chrome. Everything is fine on `0.1.0`.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/3724558/235980934-7b5aeb1f-e81d-4a4d-a647-0a7958f946fa.png">
